# Generated by Django 4.0.2 on 2022-02-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='main_content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
