# Generated by Django 4.0.2 on 2022-02-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_yangiliklar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
